INSERT INTO INFORMATION_SCHEMA.TABLE_TYPES (TYPE) VALUES ('TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLE_TYPES (TYPE) VALUES ('TABLE LINK');
INSERT INTO INFORMATION_SCHEMA.TABLE_TYPES (TYPE) VALUES ('SYSTEM TABLE');
INSERT INTO INFORMATION_SCHEMA.TABLE_TYPES (TYPE) VALUES ('VIEW');
INSERT INTO INFORMATION_SCHEMA.TABLE_TYPES (TYPE) VALUES ('EXTERNAL');